logging:
  level:
    root: info
    com.ssongman.batch: debug

spring:
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    url: "jdbc:mysql://localhost:3306/SongTest?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul"
    username: root
    password: rootpass
#    hikari:
#      auto-commit: false
#      connection-test-query: SELECT 1
#      minimum-idle: 10
#      maximum-pool-size: 50
#      pool-name: songworld
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update       # DDL(create, alter, drop) 정의 시, DB의 고유 기능을 사용할 수 있음
    properties:
      hibernate:
        format_sql: true


    